language: go

services:
- docker

go:
- 1.11.x
- 1.12.x

env:
- GO111MODULE=on

before_install:
- make devtools

#install:
# - go get github.com/gogo/protobuf/protoc-gen-gofast
#- go get github.com/gogo/protobuf/protoc-gen-gogofast

script:
- gotestsum -f short-verbose -- -race -timeout=20m -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
