language: go
go:
- 1.7.x
- 1.8.x
before_install:
- .travis/install-protoc.sh 3.3.1
install:
- go get github.com/gogo/protobuf/protoc-gen-gofast
- go get github.com/gogo/protobuf/protoc-gen-gogofast

script:
- go generate
- ./.travis/coverage
after_success:
- bash <(curl -s https://codecov.io/bash)
