// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rapid.proto

package remoting

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinStatusCode int32

const (
	JoinStatusCode_HOSTNAME_ALREADY_IN_RING JoinStatusCode = 0
	JoinStatusCode_UUID_ALREADY_IN_RING     JoinStatusCode = 1
	JoinStatusCode_SAFE_TO_JOIN             JoinStatusCode = 2
	JoinStatusCode_CONFIG_CHANGED           JoinStatusCode = 3
	JoinStatusCode_MEMBERSHIP_REJECTED      JoinStatusCode = 4
)

var JoinStatusCode_name = map[int32]string{
	0: "HOSTNAME_ALREADY_IN_RING",
	1: "UUID_ALREADY_IN_RING",
	2: "SAFE_TO_JOIN",
	3: "CONFIG_CHANGED",
	4: "MEMBERSHIP_REJECTED",
}

var JoinStatusCode_value = map[string]int32{
	"HOSTNAME_ALREADY_IN_RING": 0,
	"UUID_ALREADY_IN_RING":     1,
	"SAFE_TO_JOIN":             2,
	"CONFIG_CHANGED":           3,
	"MEMBERSHIP_REJECTED":      4,
}

func (x JoinStatusCode) String() string {
	return proto.EnumName(JoinStatusCode_name, int32(x))
}

func (JoinStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{0}
}

type EdgeStatus int32

const (
	EdgeStatus_UP   EdgeStatus = 0
	EdgeStatus_DOWN EdgeStatus = 1
)

var EdgeStatus_name = map[int32]string{
	0: "UP",
	1: "DOWN",
}

var EdgeStatus_value = map[string]int32{
	"UP":   0,
	"DOWN": 1,
}

func (x EdgeStatus) String() string {
	return proto.EnumName(EdgeStatus_name, int32(x))
}

func (EdgeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{1}
}

type NodeStatus int32

const (
	NodeStatus_OK            NodeStatus = 0
	NodeStatus_BOOTSTRAPPING NodeStatus = 1
)

var NodeStatus_name = map[int32]string{
	0: "OK",
	1: "BOOTSTRAPPING",
}

var NodeStatus_value = map[string]int32{
	"OK":            0,
	"BOOTSTRAPPING": 1,
}

func (x NodeStatus) String() string {
	return proto.EnumName(NodeStatus_name, int32(x))
}

func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{2}
}

type Endpoint struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{0}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Endpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// All-in-one message type.
type RapidRequest struct {
	// Types that are valid to be assigned to Content:
	//	*RapidRequest_PreJoinMessage
	//	*RapidRequest_JoinMessage
	//	*RapidRequest_BatchedAlertMessage
	//	*RapidRequest_ProbeMessage
	//	*RapidRequest_FastRoundPhase2BMessage
	//	*RapidRequest_Phase1AMessage
	//	*RapidRequest_Phase1BMessage
	//	*RapidRequest_Phase2AMessage
	//	*RapidRequest_Phase2BMessage
	Content              isRapidRequest_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RapidRequest) Reset()         { *m = RapidRequest{} }
func (m *RapidRequest) String() string { return proto.CompactTextString(m) }
func (*RapidRequest) ProtoMessage()    {}
func (*RapidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{1}
}

func (m *RapidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RapidRequest.Unmarshal(m, b)
}
func (m *RapidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RapidRequest.Marshal(b, m, deterministic)
}
func (m *RapidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RapidRequest.Merge(m, src)
}
func (m *RapidRequest) XXX_Size() int {
	return xxx_messageInfo_RapidRequest.Size(m)
}
func (m *RapidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RapidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RapidRequest proto.InternalMessageInfo

type isRapidRequest_Content interface {
	isRapidRequest_Content()
}

type RapidRequest_PreJoinMessage struct {
	PreJoinMessage *PreJoinMessage `protobuf:"bytes,1,opt,name=preJoinMessage,proto3,oneof"`
}

type RapidRequest_JoinMessage struct {
	JoinMessage *JoinMessage `protobuf:"bytes,2,opt,name=joinMessage,proto3,oneof"`
}

type RapidRequest_BatchedAlertMessage struct {
	BatchedAlertMessage *BatchedAlertMessage `protobuf:"bytes,3,opt,name=batchedAlertMessage,proto3,oneof"`
}

type RapidRequest_ProbeMessage struct {
	ProbeMessage *ProbeMessage `protobuf:"bytes,4,opt,name=probeMessage,proto3,oneof"`
}

type RapidRequest_FastRoundPhase2BMessage struct {
	FastRoundPhase2BMessage *FastRoundPhase2BMessage `protobuf:"bytes,5,opt,name=fastRoundPhase2bMessage,proto3,oneof"`
}

type RapidRequest_Phase1AMessage struct {
	Phase1AMessage *Phase1AMessage `protobuf:"bytes,6,opt,name=phase1aMessage,proto3,oneof"`
}

type RapidRequest_Phase1BMessage struct {
	Phase1BMessage *Phase1BMessage `protobuf:"bytes,7,opt,name=phase1bMessage,proto3,oneof"`
}

type RapidRequest_Phase2AMessage struct {
	Phase2AMessage *Phase2AMessage `protobuf:"bytes,8,opt,name=phase2aMessage,proto3,oneof"`
}

type RapidRequest_Phase2BMessage struct {
	Phase2BMessage *Phase2BMessage `protobuf:"bytes,9,opt,name=phase2bMessage,proto3,oneof"`
}

func (*RapidRequest_PreJoinMessage) isRapidRequest_Content() {}

func (*RapidRequest_JoinMessage) isRapidRequest_Content() {}

func (*RapidRequest_BatchedAlertMessage) isRapidRequest_Content() {}

func (*RapidRequest_ProbeMessage) isRapidRequest_Content() {}

func (*RapidRequest_FastRoundPhase2BMessage) isRapidRequest_Content() {}

func (*RapidRequest_Phase1AMessage) isRapidRequest_Content() {}

func (*RapidRequest_Phase1BMessage) isRapidRequest_Content() {}

func (*RapidRequest_Phase2AMessage) isRapidRequest_Content() {}

func (*RapidRequest_Phase2BMessage) isRapidRequest_Content() {}

func (m *RapidRequest) GetContent() isRapidRequest_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *RapidRequest) GetPreJoinMessage() *PreJoinMessage {
	if x, ok := m.GetContent().(*RapidRequest_PreJoinMessage); ok {
		return x.PreJoinMessage
	}
	return nil
}

func (m *RapidRequest) GetJoinMessage() *JoinMessage {
	if x, ok := m.GetContent().(*RapidRequest_JoinMessage); ok {
		return x.JoinMessage
	}
	return nil
}

func (m *RapidRequest) GetBatchedAlertMessage() *BatchedAlertMessage {
	if x, ok := m.GetContent().(*RapidRequest_BatchedAlertMessage); ok {
		return x.BatchedAlertMessage
	}
	return nil
}

func (m *RapidRequest) GetProbeMessage() *ProbeMessage {
	if x, ok := m.GetContent().(*RapidRequest_ProbeMessage); ok {
		return x.ProbeMessage
	}
	return nil
}

func (m *RapidRequest) GetFastRoundPhase2BMessage() *FastRoundPhase2BMessage {
	if x, ok := m.GetContent().(*RapidRequest_FastRoundPhase2BMessage); ok {
		return x.FastRoundPhase2BMessage
	}
	return nil
}

func (m *RapidRequest) GetPhase1AMessage() *Phase1AMessage {
	if x, ok := m.GetContent().(*RapidRequest_Phase1AMessage); ok {
		return x.Phase1AMessage
	}
	return nil
}

func (m *RapidRequest) GetPhase1BMessage() *Phase1BMessage {
	if x, ok := m.GetContent().(*RapidRequest_Phase1BMessage); ok {
		return x.Phase1BMessage
	}
	return nil
}

func (m *RapidRequest) GetPhase2AMessage() *Phase2AMessage {
	if x, ok := m.GetContent().(*RapidRequest_Phase2AMessage); ok {
		return x.Phase2AMessage
	}
	return nil
}

func (m *RapidRequest) GetPhase2BMessage() *Phase2BMessage {
	if x, ok := m.GetContent().(*RapidRequest_Phase2BMessage); ok {
		return x.Phase2BMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RapidRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RapidRequest_PreJoinMessage)(nil),
		(*RapidRequest_JoinMessage)(nil),
		(*RapidRequest_BatchedAlertMessage)(nil),
		(*RapidRequest_ProbeMessage)(nil),
		(*RapidRequest_FastRoundPhase2BMessage)(nil),
		(*RapidRequest_Phase1AMessage)(nil),
		(*RapidRequest_Phase1BMessage)(nil),
		(*RapidRequest_Phase2AMessage)(nil),
		(*RapidRequest_Phase2BMessage)(nil),
	}
}

type RapidResponse struct {
	// Types that are valid to be assigned to Content:
	//	*RapidResponse_JoinResponse
	//	*RapidResponse_Response
	//	*RapidResponse_ConsensusResponse
	//	*RapidResponse_ProbeResponse
	Content              isRapidResponse_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RapidResponse) Reset()         { *m = RapidResponse{} }
func (m *RapidResponse) String() string { return proto.CompactTextString(m) }
func (*RapidResponse) ProtoMessage()    {}
func (*RapidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{2}
}

func (m *RapidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RapidResponse.Unmarshal(m, b)
}
func (m *RapidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RapidResponse.Marshal(b, m, deterministic)
}
func (m *RapidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RapidResponse.Merge(m, src)
}
func (m *RapidResponse) XXX_Size() int {
	return xxx_messageInfo_RapidResponse.Size(m)
}
func (m *RapidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RapidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RapidResponse proto.InternalMessageInfo

type isRapidResponse_Content interface {
	isRapidResponse_Content()
}

type RapidResponse_JoinResponse struct {
	JoinResponse *JoinResponse `protobuf:"bytes,1,opt,name=joinResponse,proto3,oneof"`
}

type RapidResponse_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type RapidResponse_ConsensusResponse struct {
	ConsensusResponse *ConsensusResponse `protobuf:"bytes,3,opt,name=consensusResponse,proto3,oneof"`
}

type RapidResponse_ProbeResponse struct {
	ProbeResponse *ProbeResponse `protobuf:"bytes,4,opt,name=probeResponse,proto3,oneof"`
}

func (*RapidResponse_JoinResponse) isRapidResponse_Content() {}

func (*RapidResponse_Response) isRapidResponse_Content() {}

func (*RapidResponse_ConsensusResponse) isRapidResponse_Content() {}

func (*RapidResponse_ProbeResponse) isRapidResponse_Content() {}

func (m *RapidResponse) GetContent() isRapidResponse_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *RapidResponse) GetJoinResponse() *JoinResponse {
	if x, ok := m.GetContent().(*RapidResponse_JoinResponse); ok {
		return x.JoinResponse
	}
	return nil
}

func (m *RapidResponse) GetResponse() *Response {
	if x, ok := m.GetContent().(*RapidResponse_Response); ok {
		return x.Response
	}
	return nil
}

func (m *RapidResponse) GetConsensusResponse() *ConsensusResponse {
	if x, ok := m.GetContent().(*RapidResponse_ConsensusResponse); ok {
		return x.ConsensusResponse
	}
	return nil
}

func (m *RapidResponse) GetProbeResponse() *ProbeResponse {
	if x, ok := m.GetContent().(*RapidResponse_ProbeResponse); ok {
		return x.ProbeResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RapidResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RapidResponse_JoinResponse)(nil),
		(*RapidResponse_Response)(nil),
		(*RapidResponse_ConsensusResponse)(nil),
		(*RapidResponse_ProbeResponse)(nil),
	}
}

type NodeId struct {
	High                 int64    `protobuf:"varint,1,opt,name=high,proto3" json:"high,omitempty"`
	Low                  int64    `protobuf:"varint,2,opt,name=low,proto3" json:"low,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeId) Reset()         { *m = NodeId{} }
func (m *NodeId) String() string { return proto.CompactTextString(m) }
func (*NodeId) ProtoMessage()    {}
func (*NodeId) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{3}
}

func (m *NodeId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeId.Unmarshal(m, b)
}
func (m *NodeId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeId.Marshal(b, m, deterministic)
}
func (m *NodeId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeId.Merge(m, src)
}
func (m *NodeId) XXX_Size() int {
	return xxx_messageInfo_NodeId.Size(m)
}
func (m *NodeId) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeId.DiscardUnknown(m)
}

var xxx_messageInfo_NodeId proto.InternalMessageInfo

func (m *NodeId) GetHigh() int64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *NodeId) GetLow() int64 {
	if m != nil {
		return m.Low
	}
	return 0
}

// TODO: JoinMessage and JoinResponse are overloaded because they are being used
// for phase 1 and 2 of the bootstrap.
type PreJoinMessage struct {
	Sender               *Endpoint `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	NodeId               *NodeId   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	RingNumber           []int32   `protobuf:"varint,3,rep,packed,name=ringNumber,proto3" json:"ringNumber,omitempty"`
	ConfigurationId      int64     `protobuf:"varint,4,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PreJoinMessage) Reset()         { *m = PreJoinMessage{} }
func (m *PreJoinMessage) String() string { return proto.CompactTextString(m) }
func (*PreJoinMessage) ProtoMessage()    {}
func (*PreJoinMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{4}
}

func (m *PreJoinMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreJoinMessage.Unmarshal(m, b)
}
func (m *PreJoinMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreJoinMessage.Marshal(b, m, deterministic)
}
func (m *PreJoinMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreJoinMessage.Merge(m, src)
}
func (m *PreJoinMessage) XXX_Size() int {
	return xxx_messageInfo_PreJoinMessage.Size(m)
}
func (m *PreJoinMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PreJoinMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PreJoinMessage proto.InternalMessageInfo

func (m *PreJoinMessage) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *PreJoinMessage) GetNodeId() *NodeId {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *PreJoinMessage) GetRingNumber() []int32 {
	if m != nil {
		return m.RingNumber
	}
	return nil
}

func (m *PreJoinMessage) GetConfigurationId() int64 {
	if m != nil {
		return m.ConfigurationId
	}
	return 0
}

type JoinMessage struct {
	Sender               *Endpoint `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	NodeId               *NodeId   `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	RingNumber           []int32   `protobuf:"varint,3,rep,packed,name=ringNumber,proto3" json:"ringNumber,omitempty"`
	ConfigurationId      int64     `protobuf:"varint,4,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinMessage) Reset()         { *m = JoinMessage{} }
func (m *JoinMessage) String() string { return proto.CompactTextString(m) }
func (*JoinMessage) ProtoMessage()    {}
func (*JoinMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{5}
}

func (m *JoinMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinMessage.Unmarshal(m, b)
}
func (m *JoinMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinMessage.Marshal(b, m, deterministic)
}
func (m *JoinMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinMessage.Merge(m, src)
}
func (m *JoinMessage) XXX_Size() int {
	return xxx_messageInfo_JoinMessage.Size(m)
}
func (m *JoinMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinMessage.DiscardUnknown(m)
}

var xxx_messageInfo_JoinMessage proto.InternalMessageInfo

func (m *JoinMessage) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *JoinMessage) GetNodeId() *NodeId {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *JoinMessage) GetRingNumber() []int32 {
	if m != nil {
		return m.RingNumber
	}
	return nil
}

func (m *JoinMessage) GetConfigurationId() int64 {
	if m != nil {
		return m.ConfigurationId
	}
	return 0
}

func (m *JoinMessage) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type JoinResponse struct {
	Sender               *Endpoint            `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	StatusCode           JoinStatusCode       `protobuf:"varint,2,opt,name=statusCode,proto3,enum=remoting.JoinStatusCode" json:"statusCode,omitempty"`
	ConfigurationId      int64                `protobuf:"varint,3,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	Endpoints            []*Endpoint          `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Identifiers          []*NodeId            `protobuf:"bytes,5,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	ClusterMetadata      map[string]*Metadata `protobuf:"bytes,6,rep,name=clusterMetadata,proto3" json:"clusterMetadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{6}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *JoinResponse) GetStatusCode() JoinStatusCode {
	if m != nil {
		return m.StatusCode
	}
	return JoinStatusCode_HOSTNAME_ALREADY_IN_RING
}

func (m *JoinResponse) GetConfigurationId() int64 {
	if m != nil {
		return m.ConfigurationId
	}
	return 0
}

func (m *JoinResponse) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *JoinResponse) GetIdentifiers() []*NodeId {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *JoinResponse) GetClusterMetadata() map[string]*Metadata {
	if m != nil {
		return m.ClusterMetadata
	}
	return nil
}

type BatchedAlertMessage struct {
	Sender               *Endpoint       `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Messages             []*AlertMessage `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BatchedAlertMessage) Reset()         { *m = BatchedAlertMessage{} }
func (m *BatchedAlertMessage) String() string { return proto.CompactTextString(m) }
func (*BatchedAlertMessage) ProtoMessage()    {}
func (*BatchedAlertMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{7}
}

func (m *BatchedAlertMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchedAlertMessage.Unmarshal(m, b)
}
func (m *BatchedAlertMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchedAlertMessage.Marshal(b, m, deterministic)
}
func (m *BatchedAlertMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchedAlertMessage.Merge(m, src)
}
func (m *BatchedAlertMessage) XXX_Size() int {
	return xxx_messageInfo_BatchedAlertMessage.Size(m)
}
func (m *BatchedAlertMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchedAlertMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BatchedAlertMessage proto.InternalMessageInfo

func (m *BatchedAlertMessage) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *BatchedAlertMessage) GetMessages() []*AlertMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type AlertMessage struct {
	EdgeSrc              *Endpoint  `protobuf:"bytes,1,opt,name=edgeSrc,proto3" json:"edgeSrc,omitempty"`
	EdgeDst              *Endpoint  `protobuf:"bytes,2,opt,name=edgeDst,proto3" json:"edgeDst,omitempty"`
	EdgeStatus           EdgeStatus `protobuf:"varint,3,opt,name=edgeStatus,proto3,enum=remoting.EdgeStatus" json:"edgeStatus,omitempty"`
	ConfigurationId      int64      `protobuf:"varint,4,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	RingNumber           []int32    `protobuf:"varint,5,rep,packed,name=ringNumber,proto3" json:"ringNumber,omitempty"`
	NodeId               *NodeId    `protobuf:"bytes,6,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Metadata             *Metadata  `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AlertMessage) Reset()         { *m = AlertMessage{} }
func (m *AlertMessage) String() string { return proto.CompactTextString(m) }
func (*AlertMessage) ProtoMessage()    {}
func (*AlertMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{8}
}

func (m *AlertMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertMessage.Unmarshal(m, b)
}
func (m *AlertMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertMessage.Marshal(b, m, deterministic)
}
func (m *AlertMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertMessage.Merge(m, src)
}
func (m *AlertMessage) XXX_Size() int {
	return xxx_messageInfo_AlertMessage.Size(m)
}
func (m *AlertMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AlertMessage proto.InternalMessageInfo

func (m *AlertMessage) GetEdgeSrc() *Endpoint {
	if m != nil {
		return m.EdgeSrc
	}
	return nil
}

func (m *AlertMessage) GetEdgeDst() *Endpoint {
	if m != nil {
		return m.EdgeDst
	}
	return nil
}

func (m *AlertMessage) GetEdgeStatus() EdgeStatus {
	if m != nil {
		return m.EdgeStatus
	}
	return EdgeStatus_UP
}

func (m *AlertMessage) GetConfigurationId() int64 {
	if m != nil {
		return m.ConfigurationId
	}
	return 0
}

func (m *AlertMessage) GetRingNumber() []int32 {
	if m != nil {
		return m.RingNumber
	}
	return nil
}

func (m *AlertMessage) GetNodeId() *NodeId {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *AlertMessage) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{9}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type FastRoundPhase2BMessage struct {
	Sender               *Endpoint   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ConfigurationId      int64       `protobuf:"varint,2,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	Endpoints            []*Endpoint `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FastRoundPhase2BMessage) Reset()         { *m = FastRoundPhase2BMessage{} }
func (m *FastRoundPhase2BMessage) String() string { return proto.CompactTextString(m) }
func (*FastRoundPhase2BMessage) ProtoMessage()    {}
func (*FastRoundPhase2BMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{10}
}

func (m *FastRoundPhase2BMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastRoundPhase2BMessage.Unmarshal(m, b)
}
func (m *FastRoundPhase2BMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastRoundPhase2BMessage.Marshal(b, m, deterministic)
}
func (m *FastRoundPhase2BMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastRoundPhase2BMessage.Merge(m, src)
}
func (m *FastRoundPhase2BMessage) XXX_Size() int {
	return xxx_messageInfo_FastRoundPhase2BMessage.Size(m)
}
func (m *FastRoundPhase2BMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FastRoundPhase2BMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FastRoundPhase2BMessage proto.InternalMessageInfo

func (m *FastRoundPhase2BMessage) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *FastRoundPhase2BMessage) GetConfigurationId() int64 {
	if m != nil {
		return m.ConfigurationId
	}
	return 0
}

func (m *FastRoundPhase2BMessage) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// ******* Classic Paxos messages *********
type Rank struct {
	Round                int32    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	NodeIndex            int32    `protobuf:"varint,2,opt,name=nodeIndex,proto3" json:"nodeIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rank) Reset()         { *m = Rank{} }
func (m *Rank) String() string { return proto.CompactTextString(m) }
func (*Rank) ProtoMessage()    {}
func (*Rank) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{11}
}

func (m *Rank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rank.Unmarshal(m, b)
}
func (m *Rank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rank.Marshal(b, m, deterministic)
}
func (m *Rank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rank.Merge(m, src)
}
func (m *Rank) XXX_Size() int {
	return xxx_messageInfo_Rank.Size(m)
}
func (m *Rank) XXX_DiscardUnknown() {
	xxx_messageInfo_Rank.DiscardUnknown(m)
}

var xxx_messageInfo_Rank proto.InternalMessageInfo

func (m *Rank) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Rank) GetNodeIndex() int32 {
	if m != nil {
		return m.NodeIndex
	}
	return 0
}

type Phase1AMessage struct {
	Sender               *Endpoint `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ConfigurationId      int64     `protobuf:"varint,2,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	Rank                 *Rank     `protobuf:"bytes,3,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Phase1AMessage) Reset()         { *m = Phase1AMessage{} }
func (m *Phase1AMessage) String() string { return proto.CompactTextString(m) }
func (*Phase1AMessage) ProtoMessage()    {}
func (*Phase1AMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{12}
}

func (m *Phase1AMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phase1AMessage.Unmarshal(m, b)
}
func (m *Phase1AMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phase1AMessage.Marshal(b, m, deterministic)
}
func (m *Phase1AMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phase1AMessage.Merge(m, src)
}
func (m *Phase1AMessage) XXX_Size() int {
	return xxx_messageInfo_Phase1AMessage.Size(m)
}
func (m *Phase1AMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Phase1AMessage.DiscardUnknown(m)
}

var xxx_messageInfo_Phase1AMessage proto.InternalMessageInfo

func (m *Phase1AMessage) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Phase1AMessage) GetConfigurationId() int64 {
	if m != nil {
		return m.ConfigurationId
	}
	return 0
}

func (m *Phase1AMessage) GetRank() *Rank {
	if m != nil {
		return m.Rank
	}
	return nil
}

type Phase1BMessage struct {
	Sender               *Endpoint   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ConfigurationId      int64       `protobuf:"varint,2,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	Rnd                  *Rank       `protobuf:"bytes,3,opt,name=rnd,proto3" json:"rnd,omitempty"`
	Vrnd                 *Rank       `protobuf:"bytes,4,opt,name=vrnd,proto3" json:"vrnd,omitempty"`
	Vval                 []*Endpoint `protobuf:"bytes,5,rep,name=vval,proto3" json:"vval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Phase1BMessage) Reset()         { *m = Phase1BMessage{} }
func (m *Phase1BMessage) String() string { return proto.CompactTextString(m) }
func (*Phase1BMessage) ProtoMessage()    {}
func (*Phase1BMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{13}
}

func (m *Phase1BMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phase1BMessage.Unmarshal(m, b)
}
func (m *Phase1BMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phase1BMessage.Marshal(b, m, deterministic)
}
func (m *Phase1BMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phase1BMessage.Merge(m, src)
}
func (m *Phase1BMessage) XXX_Size() int {
	return xxx_messageInfo_Phase1BMessage.Size(m)
}
func (m *Phase1BMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Phase1BMessage.DiscardUnknown(m)
}

var xxx_messageInfo_Phase1BMessage proto.InternalMessageInfo

func (m *Phase1BMessage) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Phase1BMessage) GetConfigurationId() int64 {
	if m != nil {
		return m.ConfigurationId
	}
	return 0
}

func (m *Phase1BMessage) GetRnd() *Rank {
	if m != nil {
		return m.Rnd
	}
	return nil
}

func (m *Phase1BMessage) GetVrnd() *Rank {
	if m != nil {
		return m.Vrnd
	}
	return nil
}

func (m *Phase1BMessage) GetVval() []*Endpoint {
	if m != nil {
		return m.Vval
	}
	return nil
}

type Phase2AMessage struct {
	Sender               *Endpoint   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ConfigurationId      int64       `protobuf:"varint,2,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	Rnd                  *Rank       `protobuf:"bytes,3,opt,name=rnd,proto3" json:"rnd,omitempty"`
	Vval                 []*Endpoint `protobuf:"bytes,5,rep,name=vval,proto3" json:"vval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Phase2AMessage) Reset()         { *m = Phase2AMessage{} }
func (m *Phase2AMessage) String() string { return proto.CompactTextString(m) }
func (*Phase2AMessage) ProtoMessage()    {}
func (*Phase2AMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{14}
}

func (m *Phase2AMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phase2AMessage.Unmarshal(m, b)
}
func (m *Phase2AMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phase2AMessage.Marshal(b, m, deterministic)
}
func (m *Phase2AMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phase2AMessage.Merge(m, src)
}
func (m *Phase2AMessage) XXX_Size() int {
	return xxx_messageInfo_Phase2AMessage.Size(m)
}
func (m *Phase2AMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Phase2AMessage.DiscardUnknown(m)
}

var xxx_messageInfo_Phase2AMessage proto.InternalMessageInfo

func (m *Phase2AMessage) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Phase2AMessage) GetConfigurationId() int64 {
	if m != nil {
		return m.ConfigurationId
	}
	return 0
}

func (m *Phase2AMessage) GetRnd() *Rank {
	if m != nil {
		return m.Rnd
	}
	return nil
}

func (m *Phase2AMessage) GetVval() []*Endpoint {
	if m != nil {
		return m.Vval
	}
	return nil
}

type Phase2BMessage struct {
	Sender               *Endpoint   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ConfigurationId      int64       `protobuf:"varint,2,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	Rnd                  *Rank       `protobuf:"bytes,3,opt,name=rnd,proto3" json:"rnd,omitempty"`
	Endpoints            []*Endpoint `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Phase2BMessage) Reset()         { *m = Phase2BMessage{} }
func (m *Phase2BMessage) String() string { return proto.CompactTextString(m) }
func (*Phase2BMessage) ProtoMessage()    {}
func (*Phase2BMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{15}
}

func (m *Phase2BMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phase2BMessage.Unmarshal(m, b)
}
func (m *Phase2BMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phase2BMessage.Marshal(b, m, deterministic)
}
func (m *Phase2BMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phase2BMessage.Merge(m, src)
}
func (m *Phase2BMessage) XXX_Size() int {
	return xxx_messageInfo_Phase2BMessage.Size(m)
}
func (m *Phase2BMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Phase2BMessage.DiscardUnknown(m)
}

var xxx_messageInfo_Phase2BMessage proto.InternalMessageInfo

func (m *Phase2BMessage) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Phase2BMessage) GetConfigurationId() int64 {
	if m != nil {
		return m.ConfigurationId
	}
	return 0
}

func (m *Phase2BMessage) GetRnd() *Rank {
	if m != nil {
		return m.Rnd
	}
	return nil
}

func (m *Phase2BMessage) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type ConsensusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsensusResponse) Reset()         { *m = ConsensusResponse{} }
func (m *ConsensusResponse) String() string { return proto.CompactTextString(m) }
func (*ConsensusResponse) ProtoMessage()    {}
func (*ConsensusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{16}
}

func (m *ConsensusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusResponse.Unmarshal(m, b)
}
func (m *ConsensusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusResponse.Marshal(b, m, deterministic)
}
func (m *ConsensusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusResponse.Merge(m, src)
}
func (m *ConsensusResponse) XXX_Size() int {
	return xxx_messageInfo_ConsensusResponse.Size(m)
}
func (m *ConsensusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusResponse proto.InternalMessageInfo

// ******* Node Metadata *********
type Metadata struct {
	Metadata             map[string][]byte `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{17}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetMetadata() map[string][]byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ProbeMessage struct {
	Sender               *Endpoint `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Payload              [][]byte  `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProbeMessage) Reset()         { *m = ProbeMessage{} }
func (m *ProbeMessage) String() string { return proto.CompactTextString(m) }
func (*ProbeMessage) ProtoMessage()    {}
func (*ProbeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{18}
}

func (m *ProbeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeMessage.Unmarshal(m, b)
}
func (m *ProbeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeMessage.Marshal(b, m, deterministic)
}
func (m *ProbeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeMessage.Merge(m, src)
}
func (m *ProbeMessage) XXX_Size() int {
	return xxx_messageInfo_ProbeMessage.Size(m)
}
func (m *ProbeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeMessage proto.InternalMessageInfo

func (m *ProbeMessage) GetSender() *Endpoint {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *ProbeMessage) GetPayload() [][]byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ProbeResponse struct {
	Status               NodeStatus `protobuf:"varint,1,opt,name=status,proto3,enum=remoting.NodeStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProbeResponse) Reset()         { *m = ProbeResponse{} }
func (m *ProbeResponse) String() string { return proto.CompactTextString(m) }
func (*ProbeResponse) ProtoMessage()    {}
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8258ab588e437ac0, []int{19}
}

func (m *ProbeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeResponse.Unmarshal(m, b)
}
func (m *ProbeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeResponse.Marshal(b, m, deterministic)
}
func (m *ProbeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeResponse.Merge(m, src)
}
func (m *ProbeResponse) XXX_Size() int {
	return xxx_messageInfo_ProbeResponse.Size(m)
}
func (m *ProbeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeResponse proto.InternalMessageInfo

func (m *ProbeResponse) GetStatus() NodeStatus {
	if m != nil {
		return m.Status
	}
	return NodeStatus_OK
}

func init() {
	proto.RegisterEnum("remoting.JoinStatusCode", JoinStatusCode_name, JoinStatusCode_value)
	proto.RegisterEnum("remoting.EdgeStatus", EdgeStatus_name, EdgeStatus_value)
	proto.RegisterEnum("remoting.NodeStatus", NodeStatus_name, NodeStatus_value)
	proto.RegisterType((*Endpoint)(nil), "remoting.Endpoint")
	proto.RegisterType((*RapidRequest)(nil), "remoting.RapidRequest")
	proto.RegisterType((*RapidResponse)(nil), "remoting.RapidResponse")
	proto.RegisterType((*NodeId)(nil), "remoting.NodeId")
	proto.RegisterType((*PreJoinMessage)(nil), "remoting.PreJoinMessage")
	proto.RegisterType((*JoinMessage)(nil), "remoting.JoinMessage")
	proto.RegisterType((*JoinResponse)(nil), "remoting.JoinResponse")
	proto.RegisterMapType((map[string]*Metadata)(nil), "remoting.JoinResponse.ClusterMetadataEntry")
	proto.RegisterType((*BatchedAlertMessage)(nil), "remoting.BatchedAlertMessage")
	proto.RegisterType((*AlertMessage)(nil), "remoting.AlertMessage")
	proto.RegisterType((*Response)(nil), "remoting.Response")
	proto.RegisterType((*FastRoundPhase2BMessage)(nil), "remoting.FastRoundPhase2bMessage")
	proto.RegisterType((*Rank)(nil), "remoting.Rank")
	proto.RegisterType((*Phase1AMessage)(nil), "remoting.Phase1aMessage")
	proto.RegisterType((*Phase1BMessage)(nil), "remoting.Phase1bMessage")
	proto.RegisterType((*Phase2AMessage)(nil), "remoting.Phase2aMessage")
	proto.RegisterType((*Phase2BMessage)(nil), "remoting.Phase2bMessage")
	proto.RegisterType((*ConsensusResponse)(nil), "remoting.ConsensusResponse")
	proto.RegisterType((*Metadata)(nil), "remoting.Metadata")
	proto.RegisterMapType((map[string][]byte)(nil), "remoting.Metadata.MetadataEntry")
	proto.RegisterType((*ProbeMessage)(nil), "remoting.ProbeMessage")
	proto.RegisterType((*ProbeResponse)(nil), "remoting.ProbeResponse")
}

func init() { proto.RegisterFile("rapid.proto", fileDescriptor_8258ab588e437ac0) }

var fileDescriptor_8258ab588e437ac0 = []byte{
	// 1270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x4d, 0x6f, 0xe3, 0x54,
	0x17, 0x8e, 0xe3, 0x24, 0x4d, 0x4f, 0xd2, 0x4c, 0x7a, 0x9b, 0x77, 0x1a, 0xf5, 0x1d, 0xac, 0xe0,
	0x05, 0x44, 0x65, 0x14, 0x86, 0xc0, 0x62, 0x18, 0x06, 0x41, 0xbe, 0x3a, 0x49, 0x87, 0x7c, 0x70,
	0x93, 0x82, 0x58, 0xa0, 0xc8, 0x89, 0x6f, 0x13, 0xd3, 0xd4, 0x0e, 0xb6, 0x13, 0xe8, 0x8e, 0x0d,
	0x42, 0xe2, 0x17, 0xcc, 0x96, 0x7f, 0x80, 0xc4, 0x06, 0xb1, 0x62, 0xc1, 0x82, 0x25, 0x0b, 0x16,
	0x6c, 0x90, 0xa6, 0xf9, 0x05, 0x2c, 0x59, 0x22, 0xdf, 0xf8, 0xe3, 0xba, 0x76, 0x99, 0x66, 0x31,
	0x1a, 0xb1, 0xb3, 0xef, 0x79, 0xce, 0x73, 0x9f, 0x7b, 0x7c, 0x3e, 0xae, 0x21, 0xa5, 0x4b, 0x73,
	0x45, 0x2e, 0xcd, 0x75, 0xcd, 0xd4, 0x50, 0x52, 0x27, 0xe7, 0x9a, 0xa9, 0xa8, 0x93, 0x83, 0xdc,
	0x44, 0x9b, 0x68, 0x74, 0xf1, 0x75, 0xeb, 0x69, 0x6d, 0x17, 0x1f, 0x40, 0xb2, 0xa1, 0xca, 0x73,
	0x4d, 0x51, 0x4d, 0x74, 0x00, 0xc9, 0xa9, 0x66, 0x98, 0xaa, 0x74, 0x4e, 0xf2, 0x5c, 0x81, 0x2b,
	0x6e, 0x63, 0xf7, 0x1d, 0x21, 0x88, 0xcd, 0x35, 0xdd, 0xcc, 0x47, 0x0b, 0x5c, 0x31, 0x8e, 0xe9,
	0xb3, 0xf8, 0x24, 0x0e, 0x69, 0x6c, 0xed, 0x85, 0xc9, 0xe7, 0x0b, 0x62, 0x98, 0xa8, 0x0a, 0x99,
	0xb9, 0x4e, 0x8e, 0x35, 0x45, 0x6d, 0x13, 0xc3, 0x90, 0x26, 0x6b, 0x9a, 0x54, 0x39, 0x5f, 0x72,
	0x54, 0x94, 0x7a, 0x3e, 0x7b, 0x33, 0x82, 0xaf, 0x78, 0xa0, 0xb7, 0x21, 0xf5, 0x19, 0x43, 0x10,
	0xa5, 0x04, 0xff, 0xf3, 0x08, 0xfc, 0xde, 0x2c, 0x16, 0x7d, 0x08, 0x7b, 0x23, 0xc9, 0x1c, 0x4f,
	0x89, 0x5c, 0x99, 0x11, 0xdd, 0x74, 0x28, 0x78, 0x4a, 0xf1, 0x92, 0x47, 0x51, 0x0d, 0x82, 0x9a,
	0x11, 0x1c, 0xe6, 0x8b, 0x1e, 0x42, 0x7a, 0xae, 0x6b, 0x23, 0xe2, 0x70, 0xc5, 0x28, 0xd7, 0x6d,
	0xf6, 0x3c, 0x9e, 0xb5, 0x19, 0xc1, 0x3e, 0x34, 0xfa, 0x14, 0xf6, 0x4f, 0x25, 0xc3, 0xc4, 0xda,
	0x42, 0x95, 0x7b, 0x53, 0xc9, 0x20, 0xe5, 0x91, 0x43, 0x14, 0xa7, 0x44, 0x2f, 0x7b, 0x44, 0x47,
	0xe1, 0xc0, 0x66, 0x04, 0x5f, 0xc7, 0x41, 0xc3, 0x6d, 0xad, 0xbc, 0x21, 0x39, 0xac, 0x89, 0x40,
	0xb8, 0x7d, 0x76, 0x1a, 0x6e, 0xdf, 0x8a, 0xc7, 0xe1, 0x2a, 0xdb, 0x0a, 0xe7, 0x18, 0x05, 0x38,
	0x02, 0x3a, 0xca, 0xae, 0x8e, 0x64, 0x28, 0x47, 0x39, 0xa0, 0xa3, 0x1c, 0xd0, 0xe1, 0x45, 0x68,
	0x3b, 0x9c, 0x23, 0xa0, 0xc3, 0x5d, 0xa9, 0x6e, 0xc3, 0xd6, 0x58, 0x53, 0x4d, 0xa2, 0x9a, 0xe2,
	0x93, 0x28, 0xec, 0xd8, 0xa9, 0x69, 0xcc, 0x35, 0xd5, 0xa0, 0x5f, 0xd2, 0xca, 0x15, 0xe7, 0xdd,
	0xce, 0xcc, 0xdb, 0xfe, 0xc4, 0x72, 0xac, 0xd6, 0x97, 0x64, 0xd1, 0xe8, 0x1e, 0x24, 0x75, 0xc7,
	0x73, 0x9d, 0x92, 0xc8, 0xf3, 0x64, 0xbc, 0x5c, 0x14, 0x7a, 0x0c, 0xbb, 0x63, 0xeb, 0x41, 0x35,
	0x16, 0x86, 0xbb, 0xe9, 0x3a, 0x15, 0xff, 0xef, 0xb9, 0xd6, 0xae, 0x42, 0x9a, 0x11, 0x1c, 0xf4,
	0x43, 0xef, 0xc1, 0x0e, 0x4d, 0x2c, 0x97, 0x68, 0x9d, 0x87, 0xfb, 0x57, 0xf2, 0x90, 0x21, 0xf1,
	0xe3, 0xd9, 0xd0, 0x94, 0x20, 0xd1, 0xd1, 0x64, 0xd2, 0x92, 0xad, 0x9a, 0x9e, 0x2a, 0x93, 0x29,
	0x0d, 0x05, 0x8f, 0xe9, 0x33, 0xca, 0x02, 0x3f, 0xd3, 0xbe, 0xa0, 0x67, 0xe4, 0xb1, 0xf5, 0x28,
	0x7e, 0xcf, 0x41, 0xc6, 0x5f, 0xb5, 0xe8, 0x10, 0x12, 0x06, 0x51, 0x65, 0xa2, 0xdb, 0x51, 0x64,
	0x62, 0xe1, 0x34, 0x13, 0x6c, 0x23, 0x50, 0x11, 0x12, 0x2a, 0xdd, 0xce, 0x8e, 0x5b, 0xd6, 0xc3,
	0xae, 0x65, 0x60, 0xdb, 0x8e, 0x04, 0x00, 0x5d, 0x51, 0x27, 0x9d, 0xc5, 0xf9, 0x88, 0xe8, 0x79,
	0xbe, 0xc0, 0x17, 0xe3, 0x98, 0x59, 0x41, 0x45, 0xb8, 0x35, 0xd6, 0xd4, 0x53, 0x65, 0xb2, 0xd0,
	0x25, 0x53, 0xd1, 0xd4, 0x96, 0x4c, 0xc3, 0xc0, 0xe3, 0xab, 0xcb, 0xe2, 0x9f, 0x1c, 0xa4, 0xfe,
	0x43, 0x7a, 0x51, 0x09, 0x92, 0xe7, 0xc4, 0x94, 0x64, 0xc9, 0x94, 0xec, 0xc6, 0xc0, 0x28, 0x6c,
	0xdb, 0x16, 0xec, 0x62, 0xc4, 0x1f, 0x78, 0x48, 0xb3, 0xe9, 0xba, 0xd1, 0x01, 0xef, 0x03, 0x18,
	0xa6, 0x64, 0x2e, 0x8c, 0x9a, 0x26, 0xaf, 0x93, 0x39, 0xc3, 0x56, 0x99, 0xc5, 0xdb, 0x77, 0xed,
	0x98, 0xc1, 0x86, 0x1d, 0x88, 0x0f, 0x3f, 0xd0, 0x3d, 0xd8, 0x26, 0xf6, 0xbe, 0x46, 0x3e, 0x56,
	0xe0, 0xaf, 0x91, 0xe4, 0x81, 0x50, 0x19, 0x52, 0x8a, 0x4c, 0x54, 0x53, 0x39, 0x55, 0x88, 0x6e,
	0xe4, 0xe3, 0xd4, 0x27, 0x18, 0x7b, 0x16, 0x84, 0x4e, 0xe0, 0xd6, 0x78, 0xb6, 0x30, 0x4c, 0xa2,
	0x3b, 0x31, 0xca, 0x27, 0xa8, 0xdf, 0x6b, 0xe1, 0x55, 0x5d, 0xaa, 0xf9, 0xd1, 0x0d, 0xd5, 0xd4,
	0x2f, 0xf0, 0x55, 0x8e, 0x83, 0x8f, 0x20, 0x17, 0x06, 0xb4, 0x4a, 0xe3, 0x8c, 0x5c, 0xd8, 0x93,
	0xd1, 0x7a, 0x44, 0x45, 0x88, 0x2f, 0xa5, 0xd9, 0x22, 0xa4, 0x25, 0xb8, 0x1f, 0x6d, 0x0d, 0x78,
	0x10, 0xbd, 0xcf, 0x89, 0x0b, 0xd8, 0x0b, 0x99, 0x3c, 0x1b, 0x7d, 0xbb, 0xb2, 0x95, 0x28, 0xd4,
	0xcd, 0xa0, 0x09, 0xe7, 0x6b, 0x60, 0x2c, 0x2b, 0x76, 0x71, 0xe2, 0x2f, 0x51, 0x48, 0xfb, 0x36,
	0xbc, 0x0b, 0x5b, 0x44, 0x9e, 0x90, 0xbe, 0x3e, 0xfe, 0x97, 0x1d, 0x1d, 0x88, 0x83, 0xae, 0x1b,
	0x66, 0xf0, 0x94, 0x7e, 0x74, 0xdd, 0x30, 0xd1, 0x5b, 0x00, 0xd4, 0x91, 0x26, 0x0d, 0xcd, 0x8e,
	0x4c, 0x39, 0xc7, 0x38, 0xb8, 0x36, 0xcc, 0xe0, 0x36, 0xa8, 0x14, 0x7f, 0xcd, 0xc5, 0x43, 0x6a,
	0xce, 0xa9, 0xde, 0xc4, 0x33, 0xaa, 0x97, 0xad, 0xb9, 0xad, 0x1b, 0xd4, 0x1c, 0x40, 0xd2, 0xc9,
	0x23, 0xf1, 0x3b, 0x0e, 0xf6, 0xaf, 0x99, 0xd7, 0x1b, 0xf6, 0x9a, 0xc0, 0xb9, 0xa3, 0x37, 0x28,
	0x28, 0xfe, 0x06, 0x05, 0x25, 0x3e, 0x80, 0x18, 0x96, 0xd4, 0x33, 0x94, 0x83, 0xb8, 0x6e, 0xc9,
	0xa4, 0x72, 0xe2, 0x78, 0xfd, 0x82, 0xee, 0xc0, 0x36, 0x8d, 0x83, 0x2a, 0x93, 0x2f, 0xed, 0x3b,
	0x9d, 0xb7, 0x20, 0x7e, 0x6b, 0xb5, 0x7c, 0xff, 0x3d, 0xe1, 0xf9, 0x1c, 0x4b, 0x84, 0x98, 0x2e,
	0xa9, 0x67, 0xf6, 0x5c, 0xcc, 0x30, 0x23, 0x55, 0x52, 0xcf, 0x30, 0xb5, 0x89, 0xbf, 0xbb, 0x62,
	0x9e, 0x73, 0x8c, 0x0b, 0xc0, 0xeb, 0xaa, 0x7c, 0x8d, 0x16, 0xcb, 0x64, 0xc9, 0x5d, 0x5a, 0x90,
	0x58, 0xb8, 0x5c, 0xcb, 0x86, 0x5e, 0x81, 0xd8, 0x72, 0x29, 0xcd, 0xec, 0x0e, 0x16, 0xa6, 0x8c,
	0xda, 0xd7, 0x63, 0xd5, 0x7f, 0x07, 0x7a, 0x51, 0xc7, 0xba, 0xa9, 0xe4, 0x9f, 0x5c, 0xc9, 0x2f,
	0xfc, 0x4b, 0x6c, 0x3c, 0x60, 0xc4, 0x3d, 0xd8, 0x0d, 0x5c, 0xb6, 0xc4, 0xaf, 0x39, 0x48, 0x3a,
	0xb5, 0x8e, 0x1e, 0x32, 0x1d, 0x81, 0xa3, 0x94, 0x85, 0x60, 0x47, 0x28, 0xf9, 0x87, 0x87, 0xeb,
	0x71, 0xf0, 0x0e, 0xec, 0x3c, 0x6b, 0x5c, 0xe4, 0xd8, 0x71, 0x91, 0x66, 0x47, 0xc3, 0x00, 0xd2,
	0xec, 0x8f, 0xc4, 0x46, 0x61, 0xcd, 0xc3, 0xd6, 0x5c, 0xba, 0x98, 0x69, 0x92, 0x4c, 0x1b, 0x43,
	0x1a, 0x3b, 0xaf, 0xe2, 0xbb, 0xb0, 0xe3, 0xbb, 0x16, 0xa2, 0xbb, 0x90, 0x58, 0x8f, 0x73, 0x4a,
	0xeb, 0xeb, 0xcc, 0x56, 0x77, 0xb4, 0x3b, 0xb3, 0x8d, 0x39, 0xfc, 0x86, 0x83, 0x8c, 0xff, 0x36,
	0x80, 0xee, 0x40, 0xbe, 0xd9, 0xed, 0x0f, 0x3a, 0x95, 0x76, 0x63, 0x58, 0xf9, 0x00, 0x37, 0x2a,
	0xf5, 0x4f, 0x86, 0xad, 0xce, 0x10, 0xb7, 0x3a, 0x8f, 0xb2, 0x11, 0x94, 0x87, 0xdc, 0xc9, 0x49,
	0xab, 0x1e, 0xb0, 0x70, 0x28, 0x0b, 0xe9, 0x7e, 0xe5, 0xa8, 0x31, 0x1c, 0x74, 0x87, 0xc7, 0xdd,
	0x56, 0x27, 0x1b, 0x45, 0x08, 0x32, 0xb5, 0x6e, 0xe7, 0xa8, 0xf5, 0x68, 0x58, 0x6b, 0x56, 0x3a,
	0x8f, 0x1a, 0xf5, 0x2c, 0x8f, 0xf6, 0x61, 0xaf, 0xdd, 0x68, 0x57, 0x1b, 0xb8, 0xdf, 0x6c, 0xf5,
	0x86, 0xb8, 0x71, 0xdc, 0xa8, 0x0d, 0x1a, 0xf5, 0x6c, 0xec, 0x50, 0x00, 0xf0, 0x26, 0x07, 0x4a,
	0x40, 0xf4, 0xa4, 0x97, 0x8d, 0xa0, 0x24, 0xc4, 0xea, 0xdd, 0x8f, 0x3b, 0x59, 0xee, 0xf0, 0x55,
	0x00, 0x4f, 0xbf, 0x65, 0xef, 0x3e, 0xce, 0x46, 0xd0, 0x2e, 0xec, 0x54, 0xbb, 0xdd, 0x41, 0x7f,
	0x80, 0x2b, 0xbd, 0x1e, 0xd5, 0x51, 0x3e, 0x81, 0xdd, 0x36, 0xb1, 0x06, 0x85, 0x31, 0x55, 0xe6,
	0x7d, 0xa2, 0x2f, 0x95, 0x31, 0x41, 0xef, 0x43, 0xca, 0x0a, 0xa5, 0xf3, 0x13, 0x7b, 0x9b, 0xcd,
	0x37, 0xef, 0xe7, 0xf6, 0x60, 0x3f, 0xb0, 0x6e, 0x27, 0x51, 0xa4, 0x7a, 0xf4, 0xc7, 0xa5, 0x10,
	0x79, 0x7a, 0x29, 0x70, 0x7f, 0x5d, 0x0a, 0xdc, 0xdf, 0x97, 0x02, 0xf7, 0xd5, 0x4a, 0xe0, 0x7e,
	0x5c, 0x09, 0xdc, 0xcf, 0x2b, 0x81, 0xfb, 0x75, 0x25, 0x70, 0xbf, 0xad, 0x04, 0xee, 0xe9, 0x4a,
	0xe0, 0x20, 0x3b, 0xd6, 0xce, 0x4b, 0x4b, 0x7d, 0x52, 0xb2, 0xff, 0xd1, 0x47, 0xd5, 0x24, 0xb6,
	0x59, 0x7b, 0xdc, 0x28, 0x41, 0xff, 0xc9, 0xdf, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x88,
	0xfa, 0xa1, 0xc2, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MembershipServiceClient is the client API for MembershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MembershipServiceClient interface {
	SendRequest(ctx context.Context, in *RapidRequest, opts ...grpc.CallOption) (*RapidResponse, error)
}

type membershipServiceClient struct {
	cc *grpc.ClientConn
}

func NewMembershipServiceClient(cc *grpc.ClientConn) MembershipServiceClient {
	return &membershipServiceClient{cc}
}

func (c *membershipServiceClient) SendRequest(ctx context.Context, in *RapidRequest, opts ...grpc.CallOption) (*RapidResponse, error) {
	out := new(RapidResponse)
	err := c.cc.Invoke(ctx, "/remoting.MembershipService/sendRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServiceServer is the server API for MembershipService service.
type MembershipServiceServer interface {
	SendRequest(context.Context, *RapidRequest) (*RapidResponse, error)
}

// UnimplementedMembershipServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMembershipServiceServer struct {
}

func (*UnimplementedMembershipServiceServer) SendRequest(ctx context.Context, req *RapidRequest) (*RapidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}

func RegisterMembershipServiceServer(s *grpc.Server, srv MembershipServiceServer) {
	s.RegisterService(&_MembershipService_serviceDesc, srv)
}

func _MembershipService_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RapidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remoting.MembershipService/SendRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).SendRequest(ctx, req.(*RapidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MembershipService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remoting.MembershipService",
	HandlerType: (*MembershipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendRequest",
			Handler:    _MembershipService_SendRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rapid.proto",
}
