// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	api "github.com/casualjim/go-rapid/api"
	mock "github.com/stretchr/testify/mock"

	remoting "github.com/casualjim/go-rapid/remoting"
)

// Detector is an autogenerated mock type for the Detector type
type Detector struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *Detector) Create(_a0 *remoting.Endpoint, _a1 api.EdgeFailureCallback) api.DetectorJob {
	ret := _m.Called(_a0, _a1)

	var r0 api.DetectorJob
	if rf, ok := ret.Get(0).(func(*remoting.Endpoint, api.EdgeFailureCallback) api.DetectorJob); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.DetectorJob)
		}
	}

	return r0
}
