// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/casualjim/go-rapid/linkfailure (interfaces: Detector)

// Package linkfailure is a generated GoMock package.
package linkfailure

import (
	context "context"
	node "github.com/casualjim/go-rapid/node"
	remoting "github.com/casualjim/go-rapid/remoting"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDetector is a mock of Detector interface
type MockDetector struct {
	ctrl     *gomock.Controller
	recorder *MockDetectorMockRecorder
}

// MockDetectorMockRecorder is the mock recorder for MockDetector
type MockDetectorMockRecorder struct {
	mock *MockDetector
}

// NewMockDetector creates a new mock instance
func NewMockDetector(ctrl *gomock.Controller) *MockDetector {
	mock := &MockDetector{ctrl: ctrl}
	mock.recorder = &MockDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDetector) EXPECT() *MockDetectorMockRecorder {
	return m.recorder
}

// CheckMonitoree mocks base method
func (m *MockDetector) CheckMonitoree(arg0 context.Context, arg1 node.Addr) error {
	ret := m.ctrl.Call(m, "CheckMonitoree", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckMonitoree indicates an expected call of CheckMonitoree
func (mr *MockDetectorMockRecorder) CheckMonitoree(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMonitoree", reflect.TypeOf((*MockDetector)(nil).CheckMonitoree), arg0, arg1)
}

// HandleProbe mocks base method
func (m *MockDetector) HandleProbe(arg0 *remoting.ProbeMessage) *remoting.ProbeResponse {
	ret := m.ctrl.Call(m, "HandleProbe", arg0)
	ret0, _ := ret[0].(*remoting.ProbeResponse)
	return ret0
}

// HandleProbe indicates an expected call of HandleProbe
func (mr *MockDetectorMockRecorder) HandleProbe(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProbe", reflect.TypeOf((*MockDetector)(nil).HandleProbe), arg0)
}

// HasFailed mocks base method
func (m *MockDetector) HasFailed(arg0 node.Addr) bool {
	ret := m.ctrl.Call(m, "HasFailed", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasFailed indicates an expected call of HasFailed
func (mr *MockDetectorMockRecorder) HasFailed(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFailed", reflect.TypeOf((*MockDetector)(nil).HasFailed), arg0)
}

// OnMembershipChange mocks base method
func (m *MockDetector) OnMembershipChange(arg0 []node.Addr) {
	m.ctrl.Call(m, "OnMembershipChange", arg0)
}

// OnMembershipChange indicates an expected call of OnMembershipChange
func (mr *MockDetectorMockRecorder) OnMembershipChange(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnMembershipChange", reflect.TypeOf((*MockDetector)(nil).OnMembershipChange), arg0)
}
