name: Docker Image CI

on:
  schedule:
    - cron: '10 7 * * 5'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        tag_with_ref: true
        tags: "latest"
        add_git_labels: true
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: casualjim/rapidbuilder
        dockerfile: hack/builder/Dockerfile
